### ISSUE TITLE
读取速度太慢

### ISSUE THREAD

**Issue by transtone** [luics/storage#8]
不知为何，我存一个简单的变量值都需要3-5秒，是使用的问题吗？

**Comment by luics** [comment]
阿里外部使用请独立部署 proxy

**Comment by transtone** [comment]
怎么独立部署呢，有文档吗？

把光把源码下载回去加载，貌似不起作用啊。

# 

找到问题了，gallery官网升级了2.0.0，一堆东西调动了。
